project_id = "ojxrevoepfcypcvaedjy"

[functions.sync-odds]
verify_jwt = false

[functions.lock-lines]
verify_jwt = false

[functions.resolve-matchup]
verify_jwt = false

[functions.resolve-event]
verify_jwt = false

[functions.sync-teams]
verify_jwt = false

[functions.start-pool]
verify_jwt = false

[functions.sync-all-odds]
verify_jwt = false
